- app/controllers/lives_controller.rb
- app/models/playing.rb
- app/models/song.rb
- app/views/lives/show.html.haml
- app/views/songs/_song.html.haml
- app/views/songs/show.html.haml
- app/views/users/show.html.haml
> Set the order of performers

- app/controllers/lives_controller.rb
- app/controllers/static_pages_controller.rb
- app/models/song.rb
> Fix the order of songs

- app/models/playing.rb
> Update the order of instruments

- app/views/layouts/_navbar.html.haml
> Fix a bug of the navber dropdown

- README.md
> #fix-typo-in-readme

- app/helpers/songs_helper.rb
issue も作らず申し訳ありません.
新人ライブで ビオラ奏者が出演するため, ビオラを追加しました. ついでに, よく出てきている楽器を追加しました.
> Add instrumnet

- app/controllers/static_pages_controller.rb
- app/views/static_pages/home.html.haml
- ホーム画面に Android アプリへリンクするバッジを追加します
- ホーム画面から曲一覧を取り除きます
- ホーム画面のレシポンシブ対応について改善します
> Add a badge of Google Play to the home

- app/helpers/application_helper.rb
- app/views/layouts/_navbar.html.haml
This closes #67 
- ログインユーザー向けに Google フォームによるフィードバックフォームへのリンクを nav bar のユーザー名のプルダウンに追加します
> Add a link to the feedback form for logged in users in the nav bar

- app/views/songs/index.html.haml
This resolves #49 
- 検索結果がない場合にその旨を伝えるようにしました
> Improve feedback when there are no results

- db/migrate/20170819085058_make_columns_not_null.rb
- db/schema.rb
> Make columns not null

- app/models/regular_meeting.rb
ひとまずエラーコード部分のみ分けました.  
トップページで500が出ないようにしています(例会教室は表示されないままです)
> fixed logging code from logger.error to Rails.logger.error

- CONTRIBUTING.md
This resolves #66 
@rhinocerosSai 意見や質問等あればお願いします🙏
> Create contributing guideline

- app/controllers/api/v1/lives_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/entries_controller.rb
- app/controllers/lives_controller.rb
- app/controllers/songs_controller.rb
- app/controllers/users_controller.rb
- app/models/live.rb
- app/models/song.rb
- app/models/user.rb
- app/views/api/v1/users/show.json.jbuilder
- app/views/layouts/_navbar.html.haml
- app/views/lives/show.html.haml
- app/views/users/show.html.haml
- spec/features/live_pages_spec.rb
- spec/models/user_spec.rb
- spec/requests/authentication_spec.rb
> Replace "future / past" with "draft / performed" and add User#performed_songs

- app/controllers/entries_controller.rb
- app/models/song.rb
- app/views/entries/_form.html.haml
- app/views/song_mailer/entry.html.haml
- app/views/song_mailer/entry.text.erb
- config/locales/ja.yml
- spec/features/entry_pages_spec.rb
- spec/mailers/song_mailer_spec.rb
resolves #131 
何時~何時まで, 何時以降など, 様々な形式で入力されるためtextareaを使いました.
> Add rehearsal time and playing time form on entry page

- app/controllers/static_pages_controller.rb
- app/views/static_pages/home.html.haml
- spec/features/live_pages_spec.rb
- spec/features/static_pages_spec.rb
- spec/features/user_pages_spec.rb
resolve #141 
---
@rhinocerosSai レビューお願いします。
> Implement "Latest Lives" section in the home

- Gemfile
- Gemfile.lock
- db/seeds.rb
> Implement db/seeds.rb

- app/views/shared/_analyticstracking.html
- app/views/shared/_analyticstracking.html.erb
> Set `userId` field for Google Analytics

- app/controllers/sessions_controller.rb
> Fix a bug of SessionsController#create

- app/views/entries/_form.html.haml
- app/views/songs/_form.html.haml
- app/views/songs/_song_detail.html.haml
- app/views/songs/_status_form.html.haml
- app/views/users/edit.html.haml
> Improve notes for forms

- app/models/playing.rb
- app/views/entries/_form.html.haml
- app/views/songs/_form.html.haml
- app/views/songs/_playings_fields.html.haml
- app/views/songs/_playings_form.html.haml
> Implement autocompletion for instruments

- app/views/entries/index.html.haml
> Improve description of the publish button

- app/controllers/password_resets_controller.rb
- spec/features/password_reset_pages_spec.rb
> Prevent not-activated users from resetting password

- public/404.html
- public/422.html
- public/500.html
> Improve error pages

- app/controllers/entries_controller.rb
- app/controllers/songs_controller.rb
- app/models/concerns/song/searchable.rb
- app/models/song/search_query.rb
- app/views/entries/_form.html.haml
- app/views/entry_mailer/entry.html.haml
- app/views/entry_mailer/entry.text.erb
- app/views/songs/_form.html.haml
- app/views/songs/index.html.haml
- db/migrate/20180305122513_add_original_to_songs.rb
- db/schema.rb
- spec/models/song_spec.rb
> Add a field `original` to songs

- app/assets/javascripts/close_alert_donation.js
- app/controllers/static_pages_controller.rb
- app/models/user.rb
- app/views/layouts/_alert_donation.html.haml
- app/views/layouts/_navbar.html.haml
- app/views/layouts/application.html.haml
- app/views/static_pages/donate.html.haml
- config/routes.rb
> Implement donation page

- Gemfile
- Gemfile.lock
- app/controllers/lives_controller.rb
- app/controllers/songs_controller.rb
- app/models/song/search_query.rb
> Introduce action_args

- app/models/song.rb
- app/models/user.rb
- app/views/songs/_form.html.haml
- app/views/songs/_song.html.haml
To aggregate methods about the relationship between a song and
a user in Song model.
> Replace User#played?(song) with Song#player?(user)

- Gemfile
- Gemfile.lock
- lib/tasks/mail.rake
Fix #219 
Because https://github.com/asakusarb/action_args/pull/24 is merged.
> Bump action_args from 2.3.0 to2.3.1

- app/policies/song_policy.rb
非管理者がエントリー中の曲を見ると, 自分以外のメンバーが表示されない問題です. 
joins を入れることで解決はしましたが, 自分だけが表示されるのが不思議です....
> Fixed problems on entry index page

- spec/requests/live_requests_spec.rb
- spec/spec_helper.rb
- spec/system/entry_system_spec.rb
- spec/system/song_system_spec.rb
> Enable tests including Elasticsearch on Travis CI

- app/models/stats.rb
- app/views/stats/show.html.haml
> Improve Stats#artist_to_count

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- app/models/concerns/song/searchable.rb
> Bump elasticsearch gems to 6.0

- spec/models/song_spec.rb
> Fix test for factory_bot 5

- db/seeds.rb
- spec/factories/songs.rb
> Remove deprecated faker classes

- app/controllers/songs_controller.rb
- app/views/songs/show.html.haml
- spec/system/song_system_spec.rb
> Catch errors of Song#more_like_this

- app/views/entries/_form.html.haml
- app/views/songs/_form.html.haml
- app/views/songs/inputs/_status.html.haml
> Show disabled forms of status and comment to admins

- app/assets/javascripts/playlist.js
- app/controllers/songs_controller.rb
- app/decorators/playing_decorator.rb
- app/decorators/song_decorator.rb
- app/mailers/entry_mailer.rb
- app/mailers/song_mailer.rb
- app/models/concerns/song_searchable.rb
- app/models/entry.rb
- app/models/live.rb
- app/models/playing.rb
- app/models/song.rb
- app/views/entry_mailer/entry.html.haml
- app/views/entry_mailer/entry.text.erb
- app/views/lives/index.html.haml
- app/views/playings/_playing.html.haml
- app/views/song_mailer/pickup_song.html.haml
- app/views/song_mailer/pickup_song.text.erb
- app/views/songs/_playlist.html.haml
- app/views/songs/_song.html.haml
- app/views/songs/inputs/_live_time_order.html.haml
- app/views/songs/show.html.haml
- lib/tasks/tweet.rake
- spec/mailers/entry_mailer_spec.rb
- spec/system/entry_system_spec.rb
- spec/system/song_system_spec.rb
resolve https://github.com/sankichi92/LiveLog/issues/450
> Exterminate `delegate`

- .travis.yml
> Improve elasticsearch command options in .travis.yml

- app/javascript/packs/application.js
- package.json
- yarn.lock
> Introduce @sentry/browser

- app/models/user.rb
- db/Schemafile
ref https://github.com/sankichi92/LiveLog/issues/671
> Drop columns from users

- app/batches/application_batch.rb
- app/batches/auth0_bulk_user_import_batch.rb
- app/models/user.rb
- db/Schemafile
ref https://github.com/sankichi92/LiveLog/issues/693
> Add Auth0BulkUserImportBatch

- app/controllers/emails_controller.rb
- app/mailers/song_mailer.rb
- app/views/emails/show.html.haml
- app/views/settings/_nav.html.haml
- app/views/shared/_error_messages.html.haml
- config/routes.rb
- spec/requests/email_requests_spec.rb
ref https://github.com/sankichi92/LiveLog/issues/693
> Implement email and notification settings page

- app/controllers/profiles_controller.rb
- spec/requests/profile_requests_spec.rb
- spec/system/settings_system_spec.rb
ref https://github.com/sankichi92/LiveLog/issues/693
> Make Auth0 user name be updated

- Gemfile
- Gemfile.lock
- app/models/song.rb
- app/views/kaminari/_first_page.html.haml
- app/views/kaminari/_gap.html.haml
- app/views/kaminari/_last_page.html.haml
- app/views/kaminari/_next_page.html.haml
- app/views/kaminari/_page.html.haml
- app/views/kaminari/_paginator.html.haml
- app/views/kaminari/_prev_page.html.haml
- app/views/shared/_alert_donation.html.haml
- app/views/songs/index.html.haml
- config/initializers/kaminari_config.rb
- config/locales/ja.yml
- spec/system/song_system_spec.rb
close https://github.com/sankichi92/LiveLog/issues/717
> Replace will paginate with kaminari

- app/assets/config/manifest.js
- app/assets/stylesheets/admin.css.scss
- app/assets/stylesheets/application.css.scss
- app/controllers/admin/home_controller.rb
- app/controllers/admin/members_controller.rb
- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/raven_context.rb
- app/decorators/user_decorator.rb
- app/javascript/packs/admin.js
- app/views/admin/members/index.html.haml
- app/views/layouts/admin.html.haml
- config/locales/ja.yml
- config/routes.rb
- package.json
- spec/requests/admin/home_request_spec.rb
- spec/requests/admin/members_request_spec.rb
- yarn.lock
ref https://github.com/sankichi92/LiveLog/issues/641
> Add pages /admin and /admin/members

- app/controllers/admin/members_controller.rb
- app/controllers/users_controller.rb
- app/javascript/packs/admin.js
- app/models/member.rb
- app/models/user.rb
- app/views/admin/members/index.html.haml
- app/views/admin/members/new.html.haml
- app/views/layouts/_flash.html.haml
- app/views/layouts/admin.html.haml
- app/views/layouts/application.html.haml
- config/routes.rb
- db/seeds.rb
- spec/models/member_spec.rb
- spec/requests/admin/members_request_spec.rb
ref https://github.com/sankichi92/LiveLog/issues/641
> Implement `add member` feature for admin

- app/assets/stylesheets/admin.css.scss
- app/controllers/admin/admins_controller.rb
- app/controllers/admin/members_controller.rb
- app/controllers/admin/users_controller.rb
- app/models/auth0_user.rb
- app/models/member.rb
- app/models/user.rb
- app/views/admin/members/index.html.haml
- config/routes.rb
- spec/requests/admin/admins_request_spec.rb
- spec/requests/admin/members_request_spec.rb
- spec/requests/admin/users_request_spec.rb
https://github.com/sankichi92/LiveLog/issues/641
> Implement member manipulation buttons for admin

- Gemfile
- Gemfile.lock
- app/controllers/entries_controller.rb
- app/models/song.rb
- db/Schemafile
close https://github.com/sankichi92/LiveLog/issues/687
> Introduce gem 'acts_as_list'

- Gemfile
- Gemfile.lock
- app/javascript/controllers/tr_link_controller.js
- app/javascript/packs/admin.js
- app/javascript/packs/application.js
- app/views/layouts/_google_adsense.html
- app/views/layouts/_google_analytics.html.erb
- app/views/layouts/admin.html.haml
- app/views/layouts/application.html.haml
- app/views/songs/edit.html.haml
- package.json
- yarn.lock
close https://github.com/sankichi92/LiveLog/issues/644
> Remove turbolinks

- app/batches/auth0_consistency_check_batch.rb
- app/controllers/sessions_controller.rb
- app/models/auth0_user.rb
- app/models/user.rb
- spec/batches/auth0_consistency_check_batch_spec.rb
- spec/requests/emails_request_spec.rb
- spec/support/helpers/auth0_user_helper.rb
close https://github.com/sankichi92/LiveLog/issues/761
> Add auth0 consistency check batch

- .github/workflows/lint.yml
> Add .github/workflows/lint.yml

- Gemfile
- Gemfile.lock
- README.md
- app/models/member.rb
after https://github.com/sankichi92/LiveLog/pull/877
> Remove Member#old_avatar

- app/models/auth0_user.rb
close https://github.com/sankichi92/LiveLog/issues/1256
https://github.com/sankichi92/LiveLog/pull/1059 の対応漏れ。
> Fix usage of Auth0::Api::V2::Users.create_user
